spring.application.name=demo
spring.application.name=triptailor-persistence-service
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/triptailor}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tripuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:trippassword}
spring.sql.init.mode=always
management.endpoints.web.exposure.include=health,info,prometheus
