apiVersion: v1
kind: Secret
metadata:
  name: {{ include "triptailor.fullname" . }}-secret
  labels:
    {{- include "triptailor.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  JWT_SECRET: {{ .Values.backend.secrets.JWT_SECRET | quote }}
  AZURE_LLM_API_KEY: {{ .Values.genaiService.secrets.AZURE_LLM_API_KEY | quote }}
