/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check service health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new traveler account
         * @description Creates a persistent traveler account with e-mail and password. Returns a bearer token to be sent as `Authorization: Bearer <token>` on subsequent requests.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with e-mail and password
         * @description Authenticates an existing traveler and returns their UUID.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an anonymous demo session
         * @description Instantly provisions a temporary traveler identity — no e-mail or password required. The returned UUID can be used identically to a registered traveler's UUID. Demo accounts and their trips are eligible for automatic cleanup after a configurable TTL.
         */
        post: operations["createDemoSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all saved trips */
        get: operations["listTrips"];
        put?: never;
        /**
         * Generate and save a new trip
         * @description Calls the GenAI API to generate a schedule, then persists the result via the Persistence API.
         */
        post: operations["generateTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the full schedule of a trip */
        get: operations["getTrip"];
        put?: never;
        post?: never;
        /** Delete a trip and all its days and activities */
        delete: operations["deleteTrip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/days/{dayId}/activities/{activityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a specific activity
         * @description Removes a single activity. The parent day and trip are preserved.
         */
        delete: operations["deleteActivity"];
        options?: never;
        head?: never;
        /**
         * Regenerate a specific activity
         * @description Fetches the current full trip from the Persistence API, then calls the GenAI API with the complete trip as context so the replacement activity does not duplicate any existing activity. The new activity is persisted via the Persistence API and returned.
         */
        patch: operations["regenerateActivity"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example UP */
            status: string;
        };
        RegisterRequest: {
            /**
             * Format: email
             * @example ada@example.com
             */
            email: string;
            /**
             * Format: password
             * @example s3cr3tP@ss
             */
            password: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example ada@example.com
             */
            email: string;
            /**
             * Format: password
             * @example s3cr3tP@ss
             */
            password: string;
        };
        AuthResponse: {
            /**
             * Format: uuid
             * @description Traveler UUID encoded as the JWT subject.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            travelerId: string;
            /**
             * @description True for accounts created via POST /auth/demo. Demo accounts may be cleaned up automatically after a TTL.
             * @example false
             */
            isDemo: boolean;
            /**
             * @description JWT bearer token signed by the App API.
             * @example eyJhbGciOiJIUzI1NiJ9...
             */
            accessToken: string;
            /** @example Bearer */
            tokenType: string;
            /**
             * Format: date-time
             * @description Token expiry. Defaults to 30 days after issue time.
             * @example 2026-06-14T10:30:00Z
             */
            expiresAt: string;
        };
        GenerationPreferences: {
            /** @example Munich */
            destination: string;
            /**
             * Format: date
             * @example 2026-05-15
             */
            startDate: string;
            /**
             * Format: date
             * @example 2026-05-18
             */
            endDate: string;
            /** @example Sporty and active */
            vibe: string;
        };
        /** @description The App API automatically attaches the full trip (fetched from the Persistence API) before forwarding to the GenAI API — the frontend only needs to supply the free-text instruction. */
        RegenerationInstruction: {
            /** @example Make this an indoor activity */
            instruction: string;
        };
        TripSummary: {
            /** Format: uuid */
            id: string;
            /** @example Munich */
            destination: string;
            /**
             * Format: date
             * @example 2026-05-15
             */
            startDate: string;
            /**
             * Format: date
             * @example 2026-05-18
             */
            endDate: string;
        };
        Trip: components["schemas"]["TripSummary"] & {
            /** @example Sporty and active */
            vibe: string;
            schedule: components["schemas"]["Schedule"];
        };
        Schedule: {
            days: components["schemas"]["Day"][];
        };
        Day: {
            /** Format: uuid */
            id: string;
            /** @example 1 */
            dayNumber: number;
            /**
             * Format: date
             * @example 2026-05-15
             */
            date: string;
            activities: components["schemas"]["Activity"][];
        };
        Activity: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description UUID of the parent Day. Set on creation; read-only thereafter.
             */
            dayId: string;
            timeBlock: components["schemas"]["TimeBlock"];
            /** @example Walking tour of the English Garden */
            title: string;
            /** @example Explore the vast parklands and enjoy a beer at the Chinese Tower. */
            description: string;
            /** @example 120 */
            durationMinutes: number;
            /** @example false */
            isIndoor?: boolean;
            /**
             * @example [
             *       "OUTDOOR",
             *       "CULTURAL"
             *     ]
             */
            tags?: components["schemas"]["ActivityTag"][];
        };
        /** @enum {string} */
        TimeBlock: "MORNING" | "NOON" | "AFTERNOON" | "EVENING" | "NIGHT";
        /** @enum {string} */
        ActivityTag: "OUTDOOR" | "INDOOR" | "CULTURAL" | "SPORTY" | "RELAXING" | "ADVENTUROUS" | "FOOD" | "SHOPPING" | "ENTERTAINMENT" | "FAMILY_FRIENDLY" | "PARTY";
        ApiError: {
            /** @example TRIP_NOT_FOUND */
            type: string;
            /** @example Trip Not Found */
            title: string;
            /** @example No trip with that ID exists for this traveler. */
            detail?: string;
            /** @example 404 */
            status: number;
        };
    };
    responses: never;
    parameters: {
        TripIdPath: string;
        DayIdPath: string;
        ActivityIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description E-mail address already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createDemoSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Demo identity created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    listTrips: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User's trip list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSummary"][];
                };
            };
        };
    };
    generateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationPreferences"];
            };
        };
        responses: {
            /** @description Trip generated and saved successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description GenAI service unavailable or returned invalid output. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full trip payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Trip not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trip not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripIdPath"];
                dayId: components["parameters"]["DayIdPath"];
                activityId: components["parameters"]["ActivityIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trip, day, or activity not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    regenerateActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripIdPath"];
                dayId: components["parameters"]["DayIdPath"];
                activityId: components["parameters"]["ActivityIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerationInstruction"];
            };
        };
        responses: {
            /** @description Replacement activity saved and returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Trip, day, or activity not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
